CREATE TABLE PRODUCT_CATEGORY(
    CATEGORY_NUM NUMBER(5) NOT NULL,
    CATEGORY_MAIN VARCHAR2(50) NOT NULL,
    CATEGORY_DETAIL VARCHAR2(50) NOT NULL,
    PRIMARY KEY(CATEGORY_NUM)
);
INSERT INTO PRODUCT_CATEGORY VALUES(1,	'비타민',	'멀티비타민');
INSERT INTO PRODUCT_CATEGORY VALUES(2,	'비타민',	'비타민B');
INSERT INTO PRODUCT_CATEGORY VALUES(3,	'비타민',	'비타민C');
INSERT INTO PRODUCT_CATEGORY VALUES(4,	'비타민',	'비타민D');
INSERT INTO PRODUCT_CATEGORY VALUES(5,	'비타민',	'기타 비타민');
INSERT INTO PRODUCT_CATEGORY VALUES(6,	'영양제',	'장건강');
INSERT INTO PRODUCT_CATEGORY VALUES(7,	'영양제',	'간건강');
INSERT INTO PRODUCT_CATEGORY VALUES(8,	'영양제',	'위건강');
INSERT INTO PRODUCT_CATEGORY VALUES(9,	'영양제',	'눈건강');
INSERT INTO PRODUCT_CATEGORY VALUES(10, '영양제',	'관절/뼈/치아');
INSERT INTO PRODUCT_CATEGORY VALUES(11, '영양제',	'면역');
INSERT INTO PRODUCT_CATEGORY VALUES(12, '영양제',	'혈행');
INSERT INTO PRODUCT_CATEGORY VALUES(13, '영양제',	'오메가3');
INSERT INTO PRODUCT_CATEGORY VALUES(14, '여성',	'여성건강');
INSERT INTO PRODUCT_CATEGORY VALUES(15, '여성',	'갱년기');
INSERT INTO PRODUCT_CATEGORY VALUES(16, '여성',	'임산부');
INSERT INTO PRODUCT_CATEGORY VALUES(17, '남성',	'남성건강');
INSERT INTO PRODUCT_CATEGORY VALUES(18, '체중관리', '슬리밍');
INSERT INTO PRODUCT_CATEGORY VALUES(19, '체중관리', '프로틴');
INSERT INTO PRODUCT_CATEGORY VALUES(20, '이너뷰티', '피부케어');
INSERT INTO PRODUCT_CATEGORY VALUES(21, '이너뷰티', '모발/기타 이너뷰티케어');
INSERT INTO PRODUCT_CATEGORY VALUES(22, '베이비/키즈', '베이비/키즈');
INSERT INTO PRODUCT_CATEGORY VALUES(23, '기타', '홍삼');
INSERT INTO PRODUCT_CATEGORY VALUES(24, '기타', '프로폴리스');

    
SELECT * FROM PRODUCT_CATEGORY;