--PRODUCT테이블의 기본키인 PRODUCT_NUM에 들어갈 넘버 자동생성
CREATE SEQUENCE PRODUCT_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1;

CREATE TABLE PRODUCT(
    PRODUCT_NUM NUMBER(5) NOT NULL,
    CATEGORY_NUM NUMBER(5) NOT NULL,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    PRODUCT_PRICE NUMBER(7) NOT NULL,
    PRODUCT_STOCK NUMBER(10) DEFAULT 0,
    PRODUCT_DESC VARCHAR(200) DEFAULT '',
    PRODUCT_HITS NUMBER(7) DEFAULT 0,
    PRODUCT_LIKE NUMBER(7) DEFAULT 0,
    PRODUCT_DATE DATE DEFAULT SYSDATE,
    PRODUCT_GRADE NUMBER(2,1) DEFAULT 0,
    PRODUCT_SALE NUMBER(12) DEFAULT 0,
    PRODUCT_SELLCOUNT NUMBER(10) DEFAULT 0,
    PRODUCT_ORIGIN VARCHAR2(30),
    PRODUCT_EXP VARCHAR2(50),
    PRIMARY KEY(PRODUCT_NUM)
);
ALTER TABLE PRODUCT 
ADD STORE_SNUM NUMBER(5);

select * from product;
--좋아요를 한 사람이 여러번 누를 수 없도록 하기 위해서 LIKE TABLE 생성..
--상품에서 좋아요 누르면 상품 번호와 좋아요 누른 사람의 ID를 저장....
--SELECT COUNT(*) FROM PRODUCT_LIKE WHERE USER_ID=#{PARAM1} AND PRODUCT_NUM=#{PARAM2} 해서 유무 구분,
CREATE TABLE PRODUCT_LIKE(
    USER_ID VARCHAR2(200) NOT NULL,
    PRODUCT_NUM NUMBER(5) NOT NULL
    );

